const KEY='healthcareProData';
const seed={user:{name:'Priya'},appointments:[],medicines:[{id:1,name:'Vitamin D',dose:'1000 IU',time:'09:00',taken:false}],family:[{id:1,name:'Lovekush',relation:'Self',age:21}],timeline:[{date:new Date().toLocaleString(),title:'Profile created',detail:'HealthCare Pro demo profile initialized.'}]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
function $(id){return document.getElementById(id)}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open')}
$('closeModal').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()}
const doctors=[
{id:1,name:'Dr. Sarah Johnson',specialty:'Cardiology',rating:4.9,exp:'12 years'},
{id:2,name:'Dr. Michael Chen',specialty:'Dermatology',rating:4.8,exp:'9 years'},
{id:3,name:'Dr. Emily Wilson',specialty:'Pediatrics',rating:4.9,exp:'11 years'},
{id:4,name:'Dr. Arjun Mehta',specialty:'General Medicine',rating:4.7,exp:'8 years'},
{id:5,name:'Dr. Neha Kapoor',specialty:'Neurology',rating:4.8,exp:'10 years'},
{id:6,name:'Dr. Daniel Lee',specialty:'Cardiology',rating:4.6,exp:'7 years'}];
function renderDoctors(){const q=$('doctorSearch').value.toLowerCase();const s=$('specialtyFilter').value;const list=doctors.filter(d=>(s==='all'||d.specialty===s)&&(d.name.toLowerCase().includes(q)||d.specialty.toLowerCase().includes(q)));$('doctorList').innerHTML=list.map(d=>`<article class="doctor-card"><div class="doctor-top"><div class="avatar">${d.name.split(' ').slice(-1)[0][0]}</div><div><b>${d.name}</b><br><small>${d.specialty} • ${d.exp}</small></div></div><div>⭐ ${d.rating}/5</div><button class="btn btn-primary bookDoctor" data-id="${d.id}">Book appointment</button></article>`).join('')||'<div class="empty">No matching doctors found.</div>';document.querySelectorAll('.bookDoctor').forEach(b=>b.onclick=()=>openBooking(+b.dataset.id))}
function openBooking(doctorId=null){const d=doctors.find(x=>x.id===doctorId)||doctors[0];openModal(`<h2>Book appointment</h2><p>Choose a doctor and appointment time.</p><form id="bookingForm" class="form"><select id="bookDoctor">${doctors.map(x=>`<option value="${x.id}" ${x.id===d.id?'selected':''}>${x.name} — ${x.specialty}</option>`).join('')}</select><input id="bookDate" type="date" required min="${new Date().toISOString().slice(0,10)}"><input id="bookTime" type="time" required><select id="bookReason"><option>Consultation</option><option>Follow-up</option><option>Routine check-up</option><option>Urgent consultation</option></select><button class="btn btn-primary">Confirm booking</button></form>`);$('bookingForm').onsubmit=e=>{e.preventDefault();const doc=doctors.find(x=>x.id==$('bookDoctor').value);const ap={id:Date.now(),doctor:doc.name,specialty:doc.specialty,date:$('bookDate').value,time:$('bookTime').value,reason:$('bookReason').value,status:'Confirmed'};data.appointments.push(ap);data.timeline.unshift({date:new Date().toLocaleString(),title:'Appointment booked',detail:`${doc.name} • ${ap.date} at ${ap.time}`});save();closeModal();toast('Appointment booked successfully');location.hash='dashboard'}}
function render(){ $('userName').textContent=data.user.name; $('upcomingCount').textContent=data.appointments.filter(a=>a.status!=='Cancelled').length; $('medicineCount').textContent=data.medicines.length; $('familyCount').textContent=data.family.length;const next=data.appointments.find(a=>a.status!=='Cancelled');$('nextAppointment').textContent=next?next.date:'—';
$('appointmentTable').innerHTML=data.appointments.length?`<div class="table-wrap"><table class="data-table"><tr><th>Date</th><th>Doctor</th><th>Specialty</th><th>Reason</th><th>Status</th><th>Action</th></tr>${data.appointments.map(a=>`<tr><td>${a.date}</td><td>${a.doctor}</td><td>${a.specialty}</td><td>${a.reason}</td><td><span class="badge ${a.status==='Cancelled'?'cancelled':''}">${a.status}</span></td><td>${a.status!=='Cancelled'?`<button class="btn btn-outline cancelAppt" data-id="${a.id}">Cancel</button>`:'—'}</td></tr>`).join('')}</table></div>`:'<div class="empty">No appointments yet. Book your first appointment.</div>';
document.querySelectorAll('.cancelAppt').forEach(b=>b.onclick=()=>{const a=data.appointments.find(x=>x.id==b.dataset.id);a.status='Cancelled';data.timeline.unshift({date:new Date().toLocaleString(),title:'Appointment cancelled',detail:a.doctor});save();toast('Appointment cancelled')});
$('medicineList').innerHTML=data.medicines.length?data.medicines.map(m=>`<div class="list-item"><div><b>${m.name}</b><br><small>${m.dose} • ${m.time}</small></div><button class="btn ${m.taken?'btn-outline':'btn-primary'} doseBtn" data-id="${m.id}">${m.taken?'Taken':'Mark taken'}</button></div>`).join(''):'<div class="empty">No medicines added.</div>';
document.querySelectorAll('.doseBtn').forEach(b=>b.onclick=()=>{const m=data.medicines.find(x=>x.id==b.dataset.id);m.taken=true;data.timeline.unshift({date:new Date().toLocaleString(),title:'Medicine dose taken',detail:`${m.name} ${m.dose}`});save();toast('Dose marked as taken')});
$('todayMeds').innerHTML=data.medicines.length?data.medicines.map(m=>`<div class="list-item"><span><b>${m.name}</b><br><small>${m.time} • ${m.dose}</small></span><span class="badge">${m.taken?'Taken':'Due'}</span></div>`).join(''):'<div class="empty">No reminders.</div>';
$('familyList').innerHTML=data.family.map(f=>`<div class="family-card"><div class="avatar">${f.name[0]}</div><h3>${f.name}</h3><p>${f.relation} • ${f.age} years</p><button class="btn btn-outline switchFamily" data-id="${f.id}">Use profile</button></div>`).join('');
document.querySelectorAll('.switchFamily').forEach(b=>b.onclick=()=>{const f=data.family.find(x=>x.id==b.dataset.id);data.user.name=f.name;save();toast(`Switched to ${f.name}'s profile`)});
$('timelineList').innerHTML=data.timeline.map(x=>`<div class="timeline-item"><small>${x.date}</small><h4>${x.title}</h4><p>${x.detail}</p></div>`).join('');}
$('doctorSearch').oninput=renderDoctors;$('specialtyFilter').onchange=renderDoctors;$('getStarted').onclick=()=>location.hash='dashboard';$('addAppointmentBtn').onclick=()=>openBooking();$('bookFromTab').onclick=()=>openBooking();$('matchBtn').onclick=()=>{location.hash='doctors';$('doctorSearch').focus();toast('Choose a specialty to find a matching doctor')};$('timelineBtn').onclick=()=>document.querySelector('[data-tab="timeline"]').click();$('quickEmergency').onclick=()=>emergency();$('emergencyBtn').onclick=emergency;
function emergency(){openModal(`<h2 class="success">Emergency Support</h2><p>If this is a real emergency, contact your local emergency service immediately.</p><div class="panel"><h3>Quick contacts</h3><p><b>Emergency:</b> 112 (India)</p><p><b>Ambulance:</b> 108 (India)</p><button class="btn danger-btn" onclick="navigator.geolocation?.getCurrentPosition(()=>toast('Location permission granted'),()=>toast('Location permission unavailable'));">Share current location</button></div>`)}
$('medicineForm').onsubmit=e=>{e.preventDefault();data.medicines.push({id:Date.now(),name:$('medName').value,dose:$('medDose').value,time:$('medTime').value,taken:false});data.timeline.unshift({date:new Date().toLocaleString(),title:'Medicine added',detail:$('medName').value});e.target.reset();save();toast('Medicine reminder added')};
$('addFamilyBtn').onclick=()=>openModal(`<h2>Add family member</h2><form id="familyForm" class="form"><input id="famName" required placeholder="Name"><input id="famRelation" required placeholder="Relation e.g. Father"><input id="famAge" required type="number" min="0" placeholder="Age"><button class="btn btn-primary">Add member</button></form>`);document.addEventListener('submit',e=>{if(e.target.id!=='familyForm')return;e.preventDefault();data.family.push({id:Date.now(),name:$('famName').value,relation:$('famRelation').value,age:$('famAge').value});save();closeModal();toast('Family member added')});
function auth(mode){openModal(`<h2>${mode==='login'?'Welcome back':'Create your account'}</h2><form id="authForm" class="form"><input id="authName" placeholder="${mode==='login'?'Your name':'Full name'}" ${mode==='login'?'':'required'}><input type="email" required placeholder="Email"><input type="password" required placeholder="Password"><button class="btn btn-primary">${mode==='login'?'Login':'Create account'}</button></form>`);$('authForm').onsubmit=e=>{e.preventDefault();const n=$('authName').value||'Guest';data.user.name=n;save();closeModal();toast(`${mode==='login'?'Logged in':'Account created'} successfully`)}}
$('loginBtn').onclick=()=>auth('login');$('signupBtn').onclick=()=>auth('signup');
document.querySelectorAll('.tab-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active')});
renderDoctors();render();
